import Header from "@/components/Header";
import "../styles/globals.css";
import Prompt from "@/components/Prompt";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
        <Header />
        <Prompt />
        {/* {children} */}
      </body>
    </html>
  );
}
